version: "3.9"

services:
  nginx:
    container_name: nginx
    command: nginx -g 'daemon off;'
    image: nginx:latest
    ports:
      - "80:80"
    restart: on-failure
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
